stages:
  - build
  - deploy

variables:
  IMAGE_NAME: "registry.gitlab.com/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME"
  TAG_NAME: "latest"
  TF_VERSION: "1.0.11"  # Обновите до последней версии, если необходимо

.build:
  stage: build
  image: docker:20.10.7
  services:
    - docker:20.10.7-dind
  variables:
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: ""
  before_script:
    - apk add --no-cache curl unzip
    - curl -o /tmp/terraform.zip https://releases.hashicorp.com/terraform/${TF_VERSION}/terraform_${TF_VERSION}_linux_amd64.zip
    - unzip /tmp/terraform.zip -d /usr/local/bin/
    - terraform --version
  script:
    - docker build -t $IMAGE_NAME:$TAG_NAME .
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" --password-stdin "$CI_REGISTRY"
    - docker push $IMAGE_NAME:$TAG_NAME
  only:
    - main

.deploy:
  stage: deploy
  script:
    - echo "Deploy stage. Add your deploy scripts here."
  only:
    - main

build:
  extends: .build

deploy:
  extends: .deploy