stages:
  - validate
  - plan
  - apply
  - destroy

variables:
  TF_VERSION: "1.9.3"
  GCP_PROJECT_ID: "gitlab-cicd-431608"
  GCP_REGION: "us-central1"
  TF_STATE_NAME: "default"
  GITLAB_ACCESS_TOKEN: "<YOUR-ACCESS-TOKEN>"

before_script:
  - apt-get update && apt-get install -y unzip curl
  - curl -o /tmp/terraform.zip https://releases.hashicorp.com/terraform/${TF_VERSION}/terraform_${TF_VERSION}_linux_amd64.zip
  - unzip /tmp/terraform.zip -d /usr/local/bin/
  - terraform --version
  - GOOGLE_APPLICATION_CREDENTIALS=$GOOGLE_CREDENTIALS
  - terraform init

validate:
  stage: validate
  script:
    - terraform validate

plan:
  stage: plan
  needs: ["validate"]
  script:
    - terraform plan -out=tfplan
  artifacts:
    paths:
      - tfplan

apply:
  stage: apply
  needs: ["plan"]
  dependencies:
    - plan
  script:
    - terraform apply -auto-approve tfplan

destroy:
  stage: destroy
  needs: ["apply"]
  script:
    - terraform destroy -auto-approve
  timeout: 10 minutes